fix

diff --git a/jenkins-lfs/playbooks/roles/ansible-gdt/vars/main.yml b/jenkins-lfs/playbooks/roles/ansible-gdt/vars/main.yml
--- a/jenkins-lfs/playbooks/roles/ansible-gdt/vars/main.yml
+++ b/jenkins-lfs/playbooks/roles/ansible-gdt/vars/main.yml
@@ -2426,8 +2426,13 @@ jenkins_jobs:
       exec_command: echo
       build_tool: true
       build_command: |
+
+        (mount | grep '/mnt/lfs/proc')    || sudo mount -t proc proc /mnt/lfs/proc
+        (mount | grep '/mnt/lfs/sys')     || sudo mount -t sysfs sysfs /mnt/lfs/sys
+        (mount | grep '/mnt/lfs/dev')     || sudo mount -t devtmpfs udev /mnt/lfs/dev
+        (mount | grep '/mnt/lfs/dev/pts') || sudo mount -t devpts devpts /mnt/lfs/dev/pts
+
         cd /mnt/lfs/sources
-        curl -O https://anduin.linuxfromscratch.org/LFS/udev-lfs-20230818.tar.xz
         rm -rf /mnt/lfs/sources/systemd-257.3 || echo "Removing systemd-257.3 directory failed, continuing anyway"
         tar -xvf /mnt/lfs/sources/systemd-257.3.tar.gz
         cp /mnt/lfs/sources/udev_systemd-257.3.sh /mnt/lfs/sources/systemd-257.3/udev_systemd-257.3.sh 
@@ -2655,73 +2660,15 @@ jenkins_jobs:
       build_tool: true
       build_command: |
         cd /mnt/lfs/sources
-        rm -rf /mnt/sources/lfs/linux-6.13.4 || echo "Removing linux-6.13.4 directory failed, continuing anyway"
+        sudo rm -rf /mnt/lfs/sources/linux-6.13.4 || echo "Removing linux-6.13.4 directory failed, continuing anyway"
         tar -xf /mnt/lfs/sources/linux-6.13.4.tar.xz
         {{ chroot_start_command }} -c '
-        cd /sources/linux-6.13.4
-          make mrproper
-          make defconfig
-          make modules_install
-          # /bin/cp /sources/conf_tmp/kernel_config_x86_64 .config
-          # make olddefconfig
-          make -j$(nproc)
-          echo "CONFIG_NET=y" >> .config
-          echo "CONFIG_INET=y" >> .config
-          echo "CONFIG_IPV6=y" >> .config
-          echo "CONFIG_NETFILTER=y" >> .config
-          echo "CONFIG_NF_CONNTRACK=y" >> .config
-          echo "CONFIG_NF_NAT=y" >> .config
-          echo "CONFIG_NETFILTER_XT_MATCH_COMMENT=y" >> .config
-          echo "CONFIG_IP_NF_TARGET_REDIRECT=y" >> .config
           
-
-          # cgroups
-          echo "CONFIG_CGROUPS=y" >> .config
-          echo "CONFIG_CGROUP_BPF=y" >> .config
-          echo "CONFIG_CGROUP_FREEZER=y" >> .config
-          echo "CONFIG_CGROUP_DEVICE=y" >> .config
-          echo "CONFIG_CGROUP_CPUACCT=y" >> .config
-          echo "CONFIG_CGROUP_PIDS=y" >> .config
-          echo "CONFIG_CPUSETS=y" >> .config
-          echo "CONFIG_MEMCG=y" >> .config
-          echo "CONFIG_MEMCG_SWAP=y" >> .config
-          echo "CONFIG_MEMCG_KMEM=y" >> .config
-          echo "CONFIG_PROC_PID_CPUSET=y" >> .config
-
-          # BPF
-          echo "CONFIG_BPF=y" >> .config
-          echo "CONFIG_BPF_SYSCALL=y" >> .config
-
-          # Namespace (Kubernetes uses isolated namespaces)
-          echo "CONFIG_NAMESPACES=y" >> .config
-          echo "CONFIG_UTS_NS=y" >> .config
-          echo "CONFIG_IPC_NS=y" >> .config
-          echo "CONFIG_USER_NS=y" >> .config
-          echo "CONFIG_PID_NS=y" >> .config
-          echo "CONFIG_NET_NS=y" >> .config
-
-          # Overlay & AUFS
-          echo "CONFIG_AUFS_FS=m" >> .config
-          echo "CONFIG_OVERLAY_FS=y" >> .config
-
-          # Loop device & devtmpfs 
-          echo "CONFIG_DEVTMPFS=y" >> .config
-          echo "CONFIG_DEVTMPFS_MOUNT=y" >> .config
-          echo "CONFIG_BLK_DEV_LOOP=y" >> .config
-
-          # Docker-related extras
-          echo "CONFIG_BRIDGE_NETFILTER=y" >> .config
-          echo "CONFIG_VETH=y" >> .config
-
-          # Kubelet / container runtime / filesystem
-          echo "CONFIG_SECCOMP=y" >> .config
-          echo "CONFIG_SECCOMP_FILTER=y" >> .config
-
-          # Compatibility with systemd, even if not required on LFS
-          echo "CONFIG_EFI_VARS=y" >> .config
-
-          # CPU, basic scheduling
-          echo "CONFIG_SCHED_AUTOGROUP=y" >> .config
+          cd /sources/linux-6.13.4
+          
+          make clean
+          /bin/cp /sources/kernel_configs/kernel_config_x86_64 .config
+          make -j$(nproc)
 
           if [ -f /boot/vmlinuz-6.13.4-lfs-12.3 ]; then
             rm -f /boot/vmlinuz-6.13.4-lfs-12.3
